apiVersion: v1
kind: Service
metadata:
  name: {{ include "aegismind.fullname" . }}-lens
  labels:
    {{- include "aegismind.labels" . | nindent 4 }}
    app.kubernetes.io/component: lens
spec:
  type: {{ .Values.service.lens.type }}
  ports:
    - port: {{ .Values.service.lens.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "aegismind.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: lens
